# This name will appear in the "Actions" tab of your GitHub repository.
name: Python CI

# This section defines the triggers for the workflow.
on:
  # Run on pushes to the main branch.
  push:
    branches:
      - main
  # Run on pull requests targeting the main branch.
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build-and-test:
    # The type of virtual machine to run the job on.
    runs-on: ubuntu-latest

    # A job is a sequence of steps.
    steps:
      # Step 1: Check out your repository code so the workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the specific version of Python you're using.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Poetry.
      # We use this action only to get the tool itself installed and configured correctly.
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Step 4: Install dependencies, including the 'dev' group.
      # This is now a separate, explicit step for clarity and correctness.
      # The --no-interaction flag is good practice for non-interactive CI environments.
      # The --sync flag ensures the virtualenv matches the lock file exactly.
      - name: Install dependencies
        run: poetry install --with dev --no-interaction --sync

      # Step 5: Run Ruff to check formatting.
      # The --check flag fails the build if code is not formatted, without changing files.
      - name: Check formatting with Ruff
        run: poetry run ruff format --check .

      # Step 6: Run Ruff to lint for potential errors and style issues.
      - name: Lint with Ruff
        run: poetry run ruff check .

      # Step 7: Run the actual tests with Pytest.
      - name: Run tests with Pytest
        run: poetry run pytest

